import * as fs from "node:fs";
import * as path from "node:path";
import type { LearnedRule } from "../types.js";

const START_MARKER = "<!-- pi-learner:start -->";
const END_MARKER = "<!-- pi-learner:end -->";

export function updateAgentsMd(
  filePath: string,
  rules: LearnedRule[],
  maxLines = 30
): { updated: boolean; ruleCount: number; lines: number } {
  const tier2Rules = rules.filter((r) => r.tier === 2);
  if (tier2Rules.length === 0) {
    return { updated: false, ruleCount: 0, lines: 0 };
  }

  // Sort by lastSeenTimestamp descending (newest first for LRU retention)
  const sorted = [...tier2Rules].sort((a, b) => b.lastSeenTimestamp - a.lastSeenTimestamp);

  // Deduplicate recommendations
  const uniqueRecommendations: string[] = [];
  const seen = new Set<string>();

  for (const rule of sorted) {
    const text = rule.recommendation.trim();
    if (!seen.has(text)) {
      seen.add(text);
      uniqueRecommendations.push(text);
    }
  }

  // Cap lines to maxLines
  const capped = uniqueRecommendations.slice(0, maxLines);

  const blockLines = [
    START_MARKER,
    "### Learned Repository Guidelines (Auto-generated by pi-learner)",
    ...capped.map((r) => `- ${r}`),
    END_MARKER,
  ];
  const blockText = blockLines.join("\n");

  let existing = "";
  if (fs.existsSync(filePath)) {
    existing = fs.readFileSync(filePath, "utf8");
  } else {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  let newContent: string;
  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    newContent = existing.slice(0, startIdx).trimEnd() + "\n\n" + blockText + "\n" + existing.slice(endIdx + END_MARKER.length).trimStart();
  } else {
    newContent = existing.trim() ? `${existing.trim()}\n\n${blockText}\n` : `${blockText}\n`;
  }

  // Atomic write via temp file
  const tmpPath = `${filePath}.tmp.${Date.now()}`;
  fs.writeFileSync(tmpPath, newContent, "utf8");
  fs.renameSync(tmpPath, filePath);

  return { updated: true, ruleCount: capped.length, lines: capped.length };
}
